### ISSUE TITLE
bug: Showing error when changing the country name in edit profile page

### ISSUE THREAD

**Issue by nimishawilson** [Quarantine-Help/quarantine-help-hybrid#52]
**Describe the bug**
When editing the county name with something other than the data fetched with API, an error is showing.
The changed country name is showing as saved after showing the error.

**To Reproduce**
 Login and navigate to profile page. Try to edit the country name.

**Expected behaviour**
Expected to load the country name (not country code).
After editing, and if showing error "Invalid choice" for changing the country name, don't show the changed data as saved.

**Screenshots**
<img alt="Error" src="https://user-images.githubusercontent.com/49469003/84118014-04089b80-aa50-11ea-82db-33de851b6f17.png" width="50%" >

**Additional context**
Store JSON locally (~10 KB) -> ﻿https://api.quarantinehelp.space/api/v1/supported-countries/
https://www.joshmorony.com/high-performance-list-filtering-in-ionic-2/

**Comment by sebinbenjamin** [comment]
I think we've got to keep a local copy of the API result from https://docs.quarantinehelp.space/#/Supported%20Countries/get_api_v1_supported_countries and maybe use [ion-searchbar](https://ionicframework.com/docs/api/searchbar) to filter the results. 

So we should display the full country name (`name`) and at the same time sent the country code (`isoAlphaTwoCode`) to the backend.```

```
"countries": [
    {
      "name": "Afghanistan",
      "isoAlphaTwoCode": "AF"
    },
  ...
  ]
```
